{% set name = "neptune-optuna" %}
{% set version = "0.9.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neptune-ai/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 5519828ddd6e125c9ab871d73ec435ee9ea09d18e74658b451130bf0ef931971

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - neptune-client >=0.9.10
    - optuna >=2.4
    - plotly

test:
  imports:
    - neptune_optuna
    - neptune_optuna.impl
  # For python packages, it is useful to run pip check. However, sometimes the
  # metadata used by pip is out of date. Thus this section is optional if it is
  # failing.
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with Optuna
  doc_url: https://docs.neptune.ai/integrations-and-supported-tools/hyperparameter-optimization/optuna
  dev_url: https://github.com/neptune-ai/neptune-optuna

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - PiotrJander
    - shnela
    - pkasprzyk
